name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT:BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


